/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendasears.capaUsuario;

import java.io.File;
import javax.swing.JOptionPane;
import tiendasears.capaNegocio.Camisa;
import tiendasears.capaNegocio.Catalogo;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import tiendasears.capaDatos.Conexion;
/**
 *
 * @author sergio
 */
public class VentanaCamisa extends javax.swing.JInternalFrame {

   //Objetos que utiliza
    Camisa camisaNueva=new Camisa();
    Catalogo catalogoNuevo= new Catalogo();
    
    public VentanaCamisa() {
        initComponents();
        //Muestro el catalogo actualizado en la tabla
        this.TablaCamisas.setModel(catalogoNuevo.obtenerInformacion("camisa"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRect6 = new org.edisoncor.gui.label.LabelRect();
        txtDescripcion1 = new org.edisoncor.gui.textField.TextField();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        labelRect1 = new org.edisoncor.gui.label.LabelRect();
        labelRect2 = new org.edisoncor.gui.label.LabelRect();
        labelRect3 = new org.edisoncor.gui.label.LabelRect();
        labelRect4 = new org.edisoncor.gui.label.LabelRect();
        labelRect5 = new org.edisoncor.gui.label.LabelRect();
        txtID = new org.edisoncor.gui.textField.TextField();
        txtPrecio = new org.edisoncor.gui.textField.TextField();
        txtTam = new org.edisoncor.gui.textField.TextField();
        txtColor = new org.edisoncor.gui.textField.TextField();
        txtDescripcion = new org.edisoncor.gui.textField.TextField();
        cmdAgregar = new org.edisoncor.gui.button.ButtonSeven();
        cmdBorrar = new org.edisoncor.gui.button.ButtonSeven();
        cmdModificar = new org.edisoncor.gui.button.ButtonSeven();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCamisas = new javax.swing.JTable();
        labelRect7 = new org.edisoncor.gui.label.LabelRect();
        txtCantidad = new org.edisoncor.gui.textField.TextField();
        labelRect8 = new org.edisoncor.gui.label.LabelRect();
        txtTemporada = new org.edisoncor.gui.textField.TextField();
        btnReporte = new org.edisoncor.gui.button.ButtonSeven();

        labelRect6.setBackground(new java.awt.Color(0, 255, 0));
        labelRect6.setText("DESCRIPCION");

        labelHeader1.setText("CAMISAS");

        labelRect1.setBackground(new java.awt.Color(0, 255, 0));
        labelRect1.setText("ID CAMISA");

        labelRect2.setBackground(new java.awt.Color(0, 255, 0));
        labelRect2.setText("PRECIO");

        labelRect3.setBackground(new java.awt.Color(0, 255, 0));
        labelRect3.setText("TAMAÑO");

        labelRect4.setBackground(new java.awt.Color(0, 255, 0));
        labelRect4.setText("COLOR");

        labelRect5.setBackground(new java.awt.Color(0, 255, 0));
        labelRect5.setText("DESCRIPCION");

        txtPrecio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrecioPropertyChange(evt);
            }
        });

        cmdAgregar.setText("AGREGAR");
        cmdAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdAgregarMouseClicked(evt);
            }
        });

        cmdBorrar.setText("BORRAR");
        cmdBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBorrarMouseClicked(evt);
            }
        });

        cmdModificar.setText("MODIFICAR");
        cmdModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdModificarMouseClicked(evt);
            }
        });

        TablaCamisas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID CAMISA", "PRECIO", "TAMAÑO", "COLOR", "DESCRIPCION", "CANTIDAD"
            }
        ));
        TablaCamisas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCamisasMouseClicked(evt);
            }
        });
        TablaCamisas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaCamisasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCamisas);
        TablaCamisas.getColumnModel().getColumn(4).setResizable(false);
        TablaCamisas.getColumnModel().getColumn(5).setResizable(false);

        labelRect7.setBackground(new java.awt.Color(0, 255, 0));
        labelRect7.setText("CANTIDAD");

        labelRect8.setBackground(new java.awt.Color(0, 255, 0));
        labelRect8.setText("TEMPORADA");

        btnReporte.setText("REPORTE");
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(panelNice1);
        panelNice1.setLayout(panelNice1Layout);
        panelNice1Layout.setHorizontalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addComponent(cmdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelRect8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRect4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTemporada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelNice1Layout.setVerticalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRect3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRect4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRect5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRect8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAgregarMouseClicked
  //Agrego los datos de la camisaNueva desde los texbox
             //Integer.parseInt sirve para convertir de String a Entero
             //camisaNueva.idCamisa=Integer.parseInt(this.txtID.getText());
        
        camisaNueva.setColor(this.txtColor.getText());
        camisaNueva.setDescripcion(this.txtDescripcion.getText());
        camisaNueva.setCantidad(Integer.parseInt(this.txtCantidad.getText())); 
        camisaNueva.setPrecio(Integer.parseInt(this.txtPrecio.getText()));
        camisaNueva.setTam(Integer.parseInt(this.txtTam.getText()));
        camisaNueva.setTemporada(this.txtTemporada.getText());
        
        //agrego a mi base de datos
        if(camisaNueva.insertarCamisa()){
            JOptionPane.showMessageDialog(null,"Se agrego la camisa");
        }else{
            JOptionPane.showMessageDialog(null,"No se pudo agregar la camisa");
        }
       //Agrego la camisa al catalogo   
      // catalogoNuevo.agregarCamisaAlCatologo(camisaNueva); 
        
       //Muestro el catalogo actualizado en la tabla
      this.TablaCamisas.setModel(catalogoNuevo.obtenerInformacion("camisa"));
       
      
    }//GEN-LAST:event_cmdAgregarMouseClicked

    private void cmdBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBorrarMouseClicked
        camisaNueva.setID(Integer.parseInt(this.txtID.getText()));
        //agrego a mi base de datos
        if(camisaNueva.borrarCamisa()){
            JOptionPane.showMessageDialog(null,"Se elimino la camisa de la base de datos");
            //Muestro el catalogo actualizado en la tabla
            this.TablaCamisas.setModel(catalogoNuevo.obtenerInformacion("camisa"));
        }else{
            JOptionPane.showMessageDialog(null,"No se pudo eliminar la camisa de la base de datos");
        }
        
    }//GEN-LAST:event_cmdBorrarMouseClicked

    private void TablaCamisasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCamisasMouseClicked
          //Codigo para que muestre lo seleccionado de la tabla en los textbox
        this.txtID.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 0).toString());
        this.txtDescripcion.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 1).toString());
        this.txtPrecio.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 2).toString());
        this.txtCantidad.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 3).toString());
        this.txtTam.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 4).toString());    
        this.txtColor.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 6).toString());
        this.txtTemporada.setText(this.TablaCamisas.getModel().getValueAt( this.TablaCamisas.getSelectedRow() , 8).toString());       

    }//GEN-LAST:event_TablaCamisasMouseClicked

    private void TablaCamisasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaCamisasKeyReleased
      
    }//GEN-LAST:event_TablaCamisasKeyReleased

    private void cmdModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdModificarMouseClicked
        JOptionPane.showMessageDialog(this,"hola si entra");
        camisaNueva.setID(Integer.parseInt(this.txtID.getText()));
        camisaNueva.setColor(this.txtColor.getText());
        camisaNueva.setDescripcion(this.txtDescripcion.getText());
        camisaNueva.setCantidad(Integer.parseInt(this.txtCantidad.getText())); 
        camisaNueva.setPrecio(Double.parseDouble(this.txtPrecio.getText()));
        camisaNueva.setTam(Integer.parseInt(this.txtTam.getText()));
        camisaNueva.setTemporada(this.txtTemporada.getText());
        
        if (camisaNueva.modificarCamisa()){
            JOptionPane.showMessageDialog(null,"Se modificaron los datos de la camisa");
            //Muestro el catalogo actualizado en la tabla
            this.TablaCamisas.setModel(catalogoNuevo.obtenerInformacion("camisa"));
        }
        else{
            JOptionPane.showMessageDialog(null,"No se pudo modificar los datos de la camisa ");
        }
        
        
    }//GEN-LAST:event_cmdModificarMouseClicked

    private void txtPrecioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrecioPropertyChange
      
    }//GEN-LAST:event_txtPrecioPropertyChange
 
    
    
//Nota IMPORTANTE: 
//Publicado el 5 de diciembre de 2008 a las 07:15 am
//He resuelto el problema yo mismo. Hay algunas inconsistencias entre iReports y Jasper Report Server.
//iReports tirar jpg del directorio donde se encuentra el jrxml. Si utiliza Jasper Reports Server y utilizar la carpeta de imágenes que necesita para cambiar el jrxml.
//<imageExpression class="java.lang.String"> </ imageExpression> <[CDATA ["PRYERLogo.jpg"]]> 
//para 
//<imageExpression class="java.lang.String"> <[CDATA ["repo: / images / PRYERLogo "]]> </ imageExpression>
//Conclusion: Hay que corregir el archivo XML de ireport con la ruta correcta donde tengas la imagen     
    private void btnReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseClicked
       try{
       
       System.out.println(Conexion.hacerConexion());
       String reporte= "src\\reportes\\productos.jrxml";
       JasperReport JAS_REP= JasperCompileManager.compileReport(reporte);
       JasperPrint JAS_PRINT= JasperFillManager.fillReport(JAS_REP, null, Conexion.databaseConnection);
       JasperViewer.viewReport(JAS_PRINT);
       }
       catch(Exception X ){
           System.out.println(X.getMessage());
       }
    }//GEN-LAST:event_btnReporteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCamisas;
    private org.edisoncor.gui.button.ButtonSeven btnReporte;
    private org.edisoncor.gui.button.ButtonSeven cmdAgregar;
    private org.edisoncor.gui.button.ButtonSeven cmdBorrar;
    private org.edisoncor.gui.button.ButtonSeven cmdModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelRect labelRect1;
    private org.edisoncor.gui.label.LabelRect labelRect2;
    private org.edisoncor.gui.label.LabelRect labelRect3;
    private org.edisoncor.gui.label.LabelRect labelRect4;
    private org.edisoncor.gui.label.LabelRect labelRect5;
    private org.edisoncor.gui.label.LabelRect labelRect6;
    private org.edisoncor.gui.label.LabelRect labelRect7;
    private org.edisoncor.gui.label.LabelRect labelRect8;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.textField.TextField txtCantidad;
    private org.edisoncor.gui.textField.TextField txtColor;
    private org.edisoncor.gui.textField.TextField txtDescripcion;
    private org.edisoncor.gui.textField.TextField txtDescripcion1;
    private org.edisoncor.gui.textField.TextField txtID;
    private org.edisoncor.gui.textField.TextField txtPrecio;
    private org.edisoncor.gui.textField.TextField txtTam;
    private org.edisoncor.gui.textField.TextField txtTemporada;
    // End of variables declaration//GEN-END:variables
}
